pipeline {

   agent any

   stages {
        

	stage("install dependencies") {
           steps {
                npm install 
            }

        }
	
       stage("Supprimer le contenu du dossier target") {
            steps {
                script {
                    //this step attempts to clean the files and directories generated by Maven during its build
                    sh "import node_module package"
		  }
            }
        }
	
	stage ("démarage de l'application"){
			steps{
				sh "npm start"
			}
		} 
   }
}
