pipeline {

   agent any

   stages {
        

	stage("install dependencies") {
           steps {
                npm install 
            }

        }
	
       stage("build and start") {
            steps {
                script {
                    //this step attempts to clean the files and directories generated by Maven during its build
                    npm start
		  }
            }
        }
	
	
   }
}
